version: '3.1'

services:

  weather:
    image: weather
    restart: always
    ports:
      - 8080:8080
  notes:
    image: notes
    restart: always
    ports:
      - 8081:8080
    environment:
      WEATHER_URL: weather:8080/weather